### ISSUE TITLE
Component names

### ISSUE THREAD

**Issue by Oksana13** [naveenkumarr05/weather-app#3]
Component names should always be multi-word:
https://vuejs.org/style-guide/rules-essential.html#use-multi-word-component-names

https://github.com/naveenkumarr05/weather-app/blob/89bbedf3d4fd693a7f39c6db777a1ad077478127/package.json#L33

**Comment by naveenkumarr05** [comment]
Okay I will update

**Comment by naveenkumarr05** [comment]
Updated

**Comment by naveenkumarr05** [comment]
Updated component names
