### ISSUE TITLE
Promise

### ISSUE THREAD

**Issue by Oksana13** [naveenkumarr05/weather-app#5]
It's better to keep all such logic in Actions, and you duplicates it there and uses Promise, so, here you can just use `try catch` block, it would be much cleaner

https://github.com/naveenkumarr05/weather-app/blob/89bbedf3d4fd693a7f39c6db777a1ad077478127/src/components/SearchField.vue#L54

**Comment by naveenkumarr05** [comment]
Okay Got it

**Comment by naveenkumarr05** [comment]
Updated logic
