### ISSUE TITLE
null vs false

### ISSUE THREAD

**Issue by Oksana13** [naveenkumarr05/weather-app#6]
It's a bit confusing. Initial value is `null`, then it's an Object when gets data from BE, and here it's a `Boolean`. It's better to add here `null` then
https://github.com/naveenkumarr05/weather-app/blob/89bbedf3d4fd693a7f39c6db777a1ad077478127/src/components/SearchField.vue#L62

**Comment by Oksana13** [comment]
Sorry, here is my mistake, `currentWeatherReport` probably is a Boolean, then it's correct.
But it's better to follow Boolean naming convention (https://levelup.gitconnected.com/knot-of-nots-avoiding-negative-names-for-boolean-methods-641896a94a42) otherwise it's really confusing.

**Comment by naveenkumarr05** [comment]
yeah Correct Got it, it is Boolean only, based on condition of currentWeatherReport , current weather report will display when click on CURRENT
