### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by Oksana13** [naveenkumarr05/weather-app#9]
As you use `getCurrentWeather(true)` only once here - good practice is to move `true` inside function and keep template cleaner

https://github.com/naveenkumarr05/weather-app/blob/89bbedf3d4fd693a7f39c6db777a1ad077478127/src/components/DayForecastView.vue#L3

**Comment by naveenkumarr05** [comment]
Got it.  Set true inside function and passing to mutations
